In [3]:
import numpy as np
import pandas as pd

In [4]:
dataset = pd.read_csv('/home/riddhirup/Downloads/Fish.csv')

In [5]:
dataset

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [6]:
dataset.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [7]:
x = dataset.iloc[:,1:7].values
y = dataset.iloc[:,0:1].values

In [8]:
x

array([[2.42000e+02, 2.32000e+01, 2.54000e+01, 3.00000e+01, 1.15200e+01,
        4.02000e+00],
       [2.90000e+02, 2.40000e+01, 2.63000e+01, 3.12000e+01, 1.24800e+01,
        4.30560e+00],
       [3.40000e+02, 2.39000e+01, 2.65000e+01, 3.11000e+01, 1.23778e+01,
        4.69610e+00],
       [3.63000e+02, 2.63000e+01, 2.90000e+01, 3.35000e+01, 1.27300e+01,
        4.45550e+00],
       [4.30000e+02, 2.65000e+01, 2.90000e+01, 3.40000e+01, 1.24440e+01,
        5.13400e+00],
       [4.50000e+02, 2.68000e+01, 2.97000e+01, 3.47000e+01, 1.36024e+01,
        4.92740e+00],
       [5.00000e+02, 2.68000e+01, 2.97000e+01, 3.45000e+01, 1.41795e+01,
        5.27850e+00],
       [3.90000e+02, 2.76000e+01, 3.00000e+01, 3.50000e+01, 1.26700e+01,
        4.69000e+00],
       [4.50000e+02, 2.76000e+01, 3.00000e+01, 3.51000e+01, 1.40049e+01,
        4.84380e+00],
       [5.00000e+02, 2.85000e+01, 3.07000e+01, 3.62000e+01, 1.42266e+01,
        4.95940e+00],
       [4.75000e+02, 2.84000e+01, 3.10000e+01, 3.6

In [9]:
y

array([['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['W

In [10]:
dataset["Species"].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

0->Bream
1->Parkki
2->Perch...


In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [12]:
ct = ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder="passthrough")
y=ct.fit_transform(y).toarray()

In [13]:
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [14]:
y.shape

(159, 7)

In [15]:
print(y)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [16]:
type(y)

numpy.ndarray

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=1)

In [18]:
x_train.shape

(111, 6)

In [19]:
y_train.shape

(111, 7)

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout

In [22]:
categorical = Sequential()

In [23]:
categorical.add(Dense(units = 6,kernel_initializer = "random_uniform",activation="relu"))
categorical.add(Dense(units = 12,kernel_initializer = "random_uniform",activation="relu"))
categorical.add(Dense(units = 12,kernel_initializer = "random_uniform",activation="relu"))
categorical.add(Dense(units = 7,kernel_initializer = "random_uniform",activation="softmax"))

In [24]:
categorical.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [25]:
history = categorical.fit(x_train,y_train,epochs=500,batch_size=32,validation_data=(x_test,y_test))

Epoch 1/500
4/4 [==============================] - 2s 339ms/step - loss: 1.9455 - accuracy: 0.2394 - val_loss: 1.9434 - val_accuracy: 0.4167
Epoch 2/500
4/4 [==============================] - 0s 17ms/step - loss: 1.9433 - accuracy: 0.3485 - val_loss: 1.9409 - val_accuracy: 0.4167
Epoch 3/500
4/4 [==============================] - 0s 17ms/step - loss: 1.9412 - accuracy: 0.3370 - val_loss: 1.9385 - val_accuracy: 0.4167
Epoch 4/500
4/4 [==============================] - 0s 16ms/step - loss: 1.9390 - accuracy: 0.3401 - val_loss: 1.9361 - val_accuracy: 0.4167
Epoch 5/500
4/4 [==============================] - 0s 16ms/step - loss: 1.9375 - accuracy: 0.3193 - val_loss: 1.9336 - val_accuracy: 0.4167
Epoch 6/500
4/4 [==============================] - 0s 16ms/step - loss: 1.9351 - accuracy: 0.3276 - val_loss: 1.9307 - val_accuracy: 0.4167
Epoch 7/500
4/4 [==============================] - 0s 16ms/step - loss: 1.9339 - accuracy: 0.3006 - val_loss: 1.9278 - val_accuracy: 0.4167
Epoch 8/500
4/4 [==

4/4 [==============================] - 0s 17ms/step - loss: 1.5124 - accuracy: 0.3280 - val_loss: 1.6161 - val_accuracy: 0.5208
Epoch 118/500
4/4 [==============================] - 0s 16ms/step - loss: 1.5388 - accuracy: 0.3270 - val_loss: 1.6137 - val_accuracy: 0.5208
Epoch 119/500
4/4 [==============================] - 0s 20ms/step - loss: 1.5162 - accuracy: 0.3437 - val_loss: 1.6116 - val_accuracy: 0.5208
Epoch 120/500
4/4 [==============================] - 0s 16ms/step - loss: 1.5500 - accuracy: 0.3749 - val_loss: 1.6089 - val_accuracy: 0.5417
Epoch 121/500
4/4 [==============================] - 0s 15ms/step - loss: 1.5224 - accuracy: 0.3562 - val_loss: 1.6077 - val_accuracy: 0.5417
Epoch 122/500
4/4 [==============================] - 0s 16ms/step - loss: 1.5262 - accuracy: 0.3571 - val_loss: 1.6051 - val_accuracy: 0.5417
Epoch 123/500
4/4 [==============================] - 0s 16ms/step - loss: 1.5130 - accuracy: 0.3894 - val_loss: 1.6022 - val_accuracy: 0.5417
Epoch 124/500
4/4 [=

Epoch 175/500
4/4 [==============================] - 0s 16ms/step - loss: 1.3760 - accuracy: 0.3706 - val_loss: 1.3765 - val_accuracy: 0.5417
Epoch 176/500
4/4 [==============================] - 0s 16ms/step - loss: 1.3645 - accuracy: 0.3852 - val_loss: 1.3728 - val_accuracy: 0.5417
Epoch 177/500
4/4 [==============================] - 0s 16ms/step - loss: 1.3500 - accuracy: 0.3820 - val_loss: 1.3705 - val_accuracy: 0.5417
Epoch 178/500
4/4 [==============================] - 0s 15ms/step - loss: 1.3344 - accuracy: 0.4091 - val_loss: 1.3680 - val_accuracy: 0.5417
Epoch 179/500
4/4 [==============================] - 0s 16ms/step - loss: 1.3666 - accuracy: 0.3591 - val_loss: 1.3671 - val_accuracy: 0.5417
Epoch 180/500
4/4 [==============================] - 0s 16ms/step - loss: 1.3282 - accuracy: 0.3883 - val_loss: 1.3654 - val_accuracy: 0.5417
Epoch 181/500
4/4 [==============================] - 0s 16ms/step - loss: 1.3456 - accuracy: 0.3721 - val_loss: 1.3634 - val_accuracy: 0.5417
Epoch 

Epoch 233/500
4/4 [==============================] - 0s 15ms/step - loss: 1.1700 - accuracy: 0.5407 - val_loss: 1.2463 - val_accuracy: 0.5833
Epoch 234/500
4/4 [==============================] - 0s 15ms/step - loss: 1.1554 - accuracy: 0.5074 - val_loss: 1.2418 - val_accuracy: 0.6042
Epoch 235/500
4/4 [==============================] - 0s 15ms/step - loss: 1.1269 - accuracy: 0.5330 - val_loss: 1.2357 - val_accuracy: 0.6042
Epoch 236/500
4/4 [==============================] - 0s 15ms/step - loss: 1.1112 - accuracy: 0.5684 - val_loss: 1.2342 - val_accuracy: 0.6042
Epoch 237/500
4/4 [==============================] - 0s 16ms/step - loss: 1.0949 - accuracy: 0.5288 - val_loss: 1.2345 - val_accuracy: 0.6042
Epoch 238/500
4/4 [==============================] - 0s 15ms/step - loss: 1.1394 - accuracy: 0.5111 - val_loss: 1.2366 - val_accuracy: 0.6042
Epoch 239/500
4/4 [==============================] - 0s 15ms/step - loss: 1.1334 - accuracy: 0.5522 - val_loss: 1.2366 - val_accuracy: 0.6042
Epoch 

Epoch 291/500
4/4 [==============================] - 0s 15ms/step - loss: 1.0051 - accuracy: 0.5652 - val_loss: 1.1405 - val_accuracy: 0.6250
Epoch 292/500
4/4 [==============================] - 0s 15ms/step - loss: 1.0657 - accuracy: 0.4850 - val_loss: 1.1384 - val_accuracy: 0.6250
Epoch 293/500
4/4 [==============================] - 0s 15ms/step - loss: 0.9776 - accuracy: 0.5808 - val_loss: 1.1370 - val_accuracy: 0.6250
Epoch 294/500
4/4 [==============================] - 0s 15ms/step - loss: 1.0013 - accuracy: 0.5620 - val_loss: 1.1356 - val_accuracy: 0.6250
Epoch 295/500
4/4 [==============================] - 0s 15ms/step - loss: 1.0422 - accuracy: 0.5464 - val_loss: 1.1354 - val_accuracy: 0.6250
Epoch 296/500
4/4 [==============================] - 0s 16ms/step - loss: 1.0171 - accuracy: 0.5516 - val_loss: 1.1320 - val_accuracy: 0.6250
Epoch 297/500
4/4 [==============================] - 0s 18ms/step - loss: 1.0372 - accuracy: 0.5214 - val_loss: 1.1316 - val_accuracy: 0.6250
Epoch 

Epoch 349/500
4/4 [==============================] - 0s 22ms/step - loss: 0.9044 - accuracy: 0.6050 - val_loss: 1.0548 - val_accuracy: 0.6250
Epoch 350/500
4/4 [==============================] - 0s 19ms/step - loss: 0.8920 - accuracy: 0.6008 - val_loss: 1.0523 - val_accuracy: 0.6458
Epoch 351/500
4/4 [==============================] - 0s 18ms/step - loss: 0.9024 - accuracy: 0.6081 - val_loss: 1.0492 - val_accuracy: 0.6458
Epoch 352/500
4/4 [==============================] - 0s 19ms/step - loss: 0.9199 - accuracy: 0.5873 - val_loss: 1.0461 - val_accuracy: 0.6458
Epoch 353/500
4/4 [==============================] - 0s 18ms/step - loss: 0.9156 - accuracy: 0.5773 - val_loss: 1.0409 - val_accuracy: 0.6458
Epoch 354/500
4/4 [==============================] - 0s 18ms/step - loss: 0.8745 - accuracy: 0.6616 - val_loss: 1.0394 - val_accuracy: 0.6458
Epoch 355/500
4/4 [==============================] - 0s 19ms/step - loss: 0.9009 - accuracy: 0.6559 - val_loss: 1.0393 - val_accuracy: 0.6667
Epoch 

Epoch 407/500
4/4 [==============================] - 0s 15ms/step - loss: 0.4748 - accuracy: 0.8342 - val_loss: 0.7694 - val_accuracy: 0.7500
Epoch 408/500
4/4 [==============================] - 0s 15ms/step - loss: 0.5296 - accuracy: 0.7925 - val_loss: 0.7645 - val_accuracy: 0.7708
Epoch 409/500
4/4 [==============================] - 0s 17ms/step - loss: 0.5648 - accuracy: 0.7977 - val_loss: 0.7549 - val_accuracy: 0.7500
Epoch 410/500
4/4 [==============================] - 0s 15ms/step - loss: 0.5360 - accuracy: 0.7988 - val_loss: 0.7503 - val_accuracy: 0.7708
Epoch 411/500
4/4 [==============================] - 0s 15ms/step - loss: 0.5144 - accuracy: 0.8404 - val_loss: 0.7453 - val_accuracy: 0.7708
Epoch 412/500
4/4 [==============================] - 0s 15ms/step - loss: 0.4958 - accuracy: 0.8217 - val_loss: 0.7420 - val_accuracy: 0.7708
Epoch 413/500
4/4 [==============================] - 0s 15ms/step - loss: 0.4788 - accuracy: 0.8467 - val_loss: 0.7412 - val_accuracy: 0.7708
Epoch 

Epoch 465/500
4/4 [==============================] - 0s 20ms/step - loss: 0.4139 - accuracy: 0.8771 - val_loss: 0.6642 - val_accuracy: 0.7708
Epoch 466/500
4/4 [==============================] - 0s 19ms/step - loss: 0.3772 - accuracy: 0.8860 - val_loss: 0.6670 - val_accuracy: 0.7708
Epoch 467/500
4/4 [==============================] - 0s 18ms/step - loss: 0.4128 - accuracy: 0.8673 - val_loss: 0.6645 - val_accuracy: 0.7708
Epoch 468/500
4/4 [==============================] - 0s 19ms/step - loss: 0.3882 - accuracy: 0.8751 - val_loss: 0.6665 - val_accuracy: 0.7708
Epoch 469/500
4/4 [==============================] - 0s 18ms/step - loss: 0.4034 - accuracy: 0.8662 - val_loss: 0.6640 - val_accuracy: 0.7708
Epoch 470/500
4/4 [==============================] - 0s 18ms/step - loss: 0.4032 - accuracy: 0.8714 - val_loss: 0.6643 - val_accuracy: 0.7500
Epoch 471/500
4/4 [==============================] - 0s 17ms/step - loss: 0.4122 - accuracy: 0.8818 - val_loss: 0.6706 - val_accuracy: 0.7708
Epoch 

In [26]:
# training accuracy high, testing low -> Overfitting
# training accuracy low, testing high -> Underfitting
# if both approx. equal --> Good

In [27]:
categorical.add(Dense(units = 6,kernel_initializer = "random_uniform",activation="relu"))
categorical.add(Dropout(0.2))
categorical.add(Dense(units = 12,kernel_initializer = "random_uniform",activation="relu"))
categorical.add(Dropout(0.2))
categorical.add(Dense(units = 24,kernel_initializer = "random_uniform",activation="relu"))
categorical.add(Dropout(0.2))
categorical.add(Dense(units = 64,kernel_initializer = "random_uniform",activation="relu"))
categorical.add(Dropout(0.2))
categorical.add(Dense(units = 7,kernel_initializer = "random_uniform",activation="softmax"))
categorical.compile(optimizer="rmsprop",loss="categorical_crossentropy",metrics=["accuracy"])

In [28]:
history = categorical.fit(x_train,y_train,epochs=1000,batch_size=100,validation_data=(x_test,y_test))

Epoch 1/1000
2/2 [==============================] - 2s 299ms/step - loss: 1.9456 - accuracy: 0.3382 - val_loss: 1.9396 - val_accuracy: 0.4167
Epoch 2/1000
2/2 [==============================] - 0s 67ms/step - loss: 1.9410 - accuracy: 0.3295 - val_loss: 1.9364 - val_accuracy: 0.4167
Epoch 3/1000
2/2 [==============================] - 0s 49ms/step - loss: 1.9380 - accuracy: 0.3229 - val_loss: 1.9323 - val_accuracy: 0.4167
Epoch 4/1000
2/2 [==============================] - 0s 57ms/step - loss: 1.9345 - accuracy: 0.3262 - val_loss: 1.9285 - val_accuracy: 0.4167
Epoch 5/1000
2/2 [==============================] - 0s 50ms/step - loss: 1.9312 - accuracy: 0.3295 - val_loss: 1.9250 - val_accuracy: 0.4167
Epoch 6/1000
2/2 [==============================] - 0s 61ms/step - loss: 1.9279 - accuracy: 0.3262 - val_loss: 1.9199 - val_accuracy: 0.4167
Epoch 7/1000
2/2 [==============================] - 0s 51ms/step - loss: 1.9243 - accuracy: 0.3262 - val_loss: 1.9140 - val_accuracy: 0.4167
Epoch 8/1000

Epoch 59/1000
2/2 [==============================] - 0s 48ms/step - loss: 1.6509 - accuracy: 0.3262 - val_loss: 1.5901 - val_accuracy: 0.4167
Epoch 60/1000
2/2 [==============================] - 0s 64ms/step - loss: 1.6354 - accuracy: 0.3229 - val_loss: 1.5859 - val_accuracy: 0.4167
Epoch 61/1000
2/2 [==============================] - 0s 58ms/step - loss: 1.6318 - accuracy: 0.3295 - val_loss: 1.5857 - val_accuracy: 0.4167
Epoch 62/1000
2/2 [==============================] - 0s 52ms/step - loss: 1.6288 - accuracy: 0.3195 - val_loss: 1.5773 - val_accuracy: 0.4167
Epoch 63/1000
2/2 [==============================] - 0s 72ms/step - loss: 1.6566 - accuracy: 0.3262 - val_loss: 1.5750 - val_accuracy: 0.4167
Epoch 64/1000
2/2 [==============================] - 0s 57ms/step - loss: 1.6464 - accuracy: 0.3229 - val_loss: 1.5699 - val_accuracy: 0.4167
Epoch 65/1000
2/2 [==============================] - 0s 58ms/step - loss: 1.5894 - accuracy: 0.3329 - val_loss: 1.5753 - val_accuracy: 0.4167
Epoch 

2/2 [==============================] - 0s 75ms/step - loss: 1.3571 - accuracy: 0.4476 - val_loss: 1.6726 - val_accuracy: 0.4583
Epoch 174/1000
2/2 [==============================] - 0s 64ms/step - loss: 1.4103 - accuracy: 0.4223 - val_loss: 1.5962 - val_accuracy: 0.4583
Epoch 175/1000
2/2 [==============================] - 0s 48ms/step - loss: 1.3470 - accuracy: 0.4416 - val_loss: 1.5356 - val_accuracy: 0.4583
Epoch 176/1000
2/2 [==============================] - 0s 49ms/step - loss: 1.3652 - accuracy: 0.4256 - val_loss: 1.5414 - val_accuracy: 0.4583
Epoch 177/1000
2/2 [==============================] - 0s 49ms/step - loss: 1.4416 - accuracy: 0.4536 - val_loss: 1.5624 - val_accuracy: 0.4583
Epoch 178/1000
2/2 [==============================] - 0s 56ms/step - loss: 1.3416 - accuracy: 0.4343 - val_loss: 1.5769 - val_accuracy: 0.4583
Epoch 179/1000
2/2 [==============================] - 0s 50ms/step - loss: 1.4140 - accuracy: 0.4256 - val_loss: 1.5968 - val_accuracy: 0.4583
Epoch 180/1000

2/2 [==============================] - 0s 48ms/step - loss: 1.1957 - accuracy: 0.5310 - val_loss: 2.0156 - val_accuracy: 0.4583
Epoch 288/1000
2/2 [==============================] - 0s 49ms/step - loss: 1.2966 - accuracy: 0.4843 - val_loss: 1.9389 - val_accuracy: 0.4583
Epoch 289/1000
2/2 [==============================] - 0s 58ms/step - loss: 1.2198 - accuracy: 0.5377 - val_loss: 1.9755 - val_accuracy: 0.4583
Epoch 290/1000
2/2 [==============================] - 0s 48ms/step - loss: 1.2268 - accuracy: 0.4690 - val_loss: 2.0978 - val_accuracy: 0.4583
Epoch 291/1000
2/2 [==============================] - 0s 61ms/step - loss: 1.3562 - accuracy: 0.4877 - val_loss: 1.9478 - val_accuracy: 0.4583
Epoch 292/1000
2/2 [==============================] - 0s 51ms/step - loss: 1.2080 - accuracy: 0.5497 - val_loss: 1.9614 - val_accuracy: 0.4583
Epoch 293/1000
2/2 [==============================] - 0s 49ms/step - loss: 1.2230 - accuracy: 0.5497 - val_loss: 1.9824 - val_accuracy: 0.4583
Epoch 294/1000

2/2 [==============================] - 0s 52ms/step - loss: 1.0445 - accuracy: 0.6618 - val_loss: 2.5699 - val_accuracy: 0.6667
Epoch 402/1000
2/2 [==============================] - 0s 47ms/step - loss: 1.0102 - accuracy: 0.6651 - val_loss: 2.6664 - val_accuracy: 0.6667
Epoch 403/1000
2/2 [==============================] - 0s 47ms/step - loss: 1.0838 - accuracy: 0.6611 - val_loss: 2.6354 - val_accuracy: 0.6667
Epoch 404/1000
2/2 [==============================] - 0s 50ms/step - loss: 1.0416 - accuracy: 0.6644 - val_loss: 2.7169 - val_accuracy: 0.6667
Epoch 405/1000
2/2 [==============================] - 0s 51ms/step - loss: 1.0655 - accuracy: 0.6524 - val_loss: 2.7673 - val_accuracy: 0.6667
Epoch 406/1000
2/2 [==============================] - 0s 49ms/step - loss: 1.0364 - accuracy: 0.6524 - val_loss: 2.2326 - val_accuracy: 0.6667
Epoch 407/1000
2/2 [==============================] - 0s 52ms/step - loss: 1.0501 - accuracy: 0.6364 - val_loss: 2.3710 - val_accuracy: 0.6667
Epoch 408/1000

2/2 [==============================] - 0s 57ms/step - loss: 0.9275 - accuracy: 0.6551 - val_loss: 3.6025 - val_accuracy: 0.6667
Epoch 516/1000
2/2 [==============================] - 0s 61ms/step - loss: 0.8727 - accuracy: 0.6558 - val_loss: 3.7300 - val_accuracy: 0.6667
Epoch 517/1000
2/2 [==============================] - 0s 48ms/step - loss: 0.9009 - accuracy: 0.6524 - val_loss: 3.9137 - val_accuracy: 0.6667
Epoch 518/1000
2/2 [==============================] - 0s 49ms/step - loss: 0.8890 - accuracy: 0.6584 - val_loss: 4.1028 - val_accuracy: 0.6667
Epoch 519/1000
2/2 [==============================] - 0s 51ms/step - loss: 0.8921 - accuracy: 0.6491 - val_loss: 4.0528 - val_accuracy: 0.6667
Epoch 520/1000
2/2 [==============================] - 0s 53ms/step - loss: 0.8319 - accuracy: 0.6578 - val_loss: 4.0736 - val_accuracy: 0.6667
Epoch 521/1000
2/2 [==============================] - 0s 48ms/step - loss: 0.8479 - accuracy: 0.6838 - val_loss: 4.0299 - val_accuracy: 0.6667
Epoch 522/1000

2/2 [==============================] - 0s 57ms/step - loss: 0.8112 - accuracy: 0.6898 - val_loss: 6.2617 - val_accuracy: 0.6667
Epoch 630/1000
2/2 [==============================] - 0s 59ms/step - loss: 0.8215 - accuracy: 0.6958 - val_loss: 6.3223 - val_accuracy: 0.6667
Epoch 631/1000
2/2 [==============================] - 0s 47ms/step - loss: 0.8131 - accuracy: 0.6965 - val_loss: 6.3550 - val_accuracy: 0.6667
Epoch 632/1000
2/2 [==============================] - 0s 54ms/step - loss: 0.8192 - accuracy: 0.7051 - val_loss: 6.3511 - val_accuracy: 0.6667
Epoch 633/1000
2/2 [==============================] - 0s 53ms/step - loss: 0.8223 - accuracy: 0.6771 - val_loss: 6.1849 - val_accuracy: 0.7083
Epoch 634/1000
2/2 [==============================] - 0s 51ms/step - loss: 0.8209 - accuracy: 0.6678 - val_loss: 6.2952 - val_accuracy: 0.6667
Epoch 635/1000
2/2 [==============================] - 0s 51ms/step - loss: 0.8170 - accuracy: 0.6925 - val_loss: 6.4176 - val_accuracy: 0.6667
Epoch 636/1000

2/2 [==============================] - 0s 51ms/step - loss: 0.7789 - accuracy: 0.7045 - val_loss: 8.9343 - val_accuracy: 0.6875
Epoch 744/1000
2/2 [==============================] - 0s 47ms/step - loss: 0.7884 - accuracy: 0.6678 - val_loss: 8.9601 - val_accuracy: 0.6875
Epoch 745/1000
2/2 [==============================] - 0s 53ms/step - loss: 0.7584 - accuracy: 0.6985 - val_loss: 9.1382 - val_accuracy: 0.6667
Epoch 746/1000
2/2 [==============================] - 0s 51ms/step - loss: 0.7642 - accuracy: 0.6524 - val_loss: 8.8959 - val_accuracy: 0.6667
Epoch 747/1000
2/2 [==============================] - 0s 53ms/step - loss: 0.8496 - accuracy: 0.6838 - val_loss: 8.5059 - val_accuracy: 0.7083
Epoch 748/1000
2/2 [==============================] - 0s 51ms/step - loss: 0.7714 - accuracy: 0.6644 - val_loss: 8.7503 - val_accuracy: 0.6875
Epoch 749/1000
2/2 [==============================] - 0s 47ms/step - loss: 0.7444 - accuracy: 0.7265 - val_loss: 8.9127 - val_accuracy: 0.7292
Epoch 750/1000

2/2 [==============================] - 0s 48ms/step - loss: 0.7224 - accuracy: 0.6985 - val_loss: 10.1452 - val_accuracy: 0.7083
Epoch 858/1000
2/2 [==============================] - 0s 51ms/step - loss: 0.7145 - accuracy: 0.7145 - val_loss: 10.3936 - val_accuracy: 0.7292
Epoch 859/1000
2/2 [==============================] - 0s 48ms/step - loss: 0.7369 - accuracy: 0.7085 - val_loss: 10.3851 - val_accuracy: 0.7292
Epoch 860/1000
2/2 [==============================] - 0s 49ms/step - loss: 0.7973 - accuracy: 0.7111 - val_loss: 10.8534 - val_accuracy: 0.7083
Epoch 861/1000
2/2 [==============================] - 0s 49ms/step - loss: 0.7746 - accuracy: 0.6965 - val_loss: 10.7235 - val_accuracy: 0.7083
Epoch 862/1000
2/2 [==============================] - 0s 53ms/step - loss: 0.8022 - accuracy: 0.6951 - val_loss: 8.5609 - val_accuracy: 0.7083
Epoch 863/1000
2/2 [==============================] - 0s 49ms/step - loss: 0.8375 - accuracy: 0.6678 - val_loss: 9.3408 - val_accuracy: 0.7083
Epoch 864

2/2 [==============================] - 0s 48ms/step - loss: 0.7494 - accuracy: 0.7111 - val_loss: 11.1602 - val_accuracy: 0.7083
Epoch 972/1000
2/2 [==============================] - 0s 48ms/step - loss: 0.8340 - accuracy: 0.6451 - val_loss: 11.2566 - val_accuracy: 0.7083
Epoch 973/1000
2/2 [==============================] - 0s 49ms/step - loss: 0.7188 - accuracy: 0.6831 - val_loss: 11.3364 - val_accuracy: 0.7083
Epoch 974/1000
2/2 [==============================] - 0s 52ms/step - loss: 0.7247 - accuracy: 0.7025 - val_loss: 11.4613 - val_accuracy: 0.7292
Epoch 975/1000
2/2 [==============================] - 0s 53ms/step - loss: 0.8150 - accuracy: 0.6491 - val_loss: 11.4408 - val_accuracy: 0.7083
Epoch 976/1000
2/2 [==============================] - 0s 57ms/step - loss: 0.7282 - accuracy: 0.6551 - val_loss: 11.5983 - val_accuracy: 0.7500
Epoch 977/1000
2/2 [==============================] - 0s 50ms/step - loss: 0.7379 - accuracy: 0.7178 - val_loss: 11.6953 - val_accuracy: 0.7292
Epoch 9

In [29]:
categorical.add(Dense(units = 6,kernel_initializer = "random_uniform",activation="relu"))
categorical.add(Dense(units = 12,kernel_initializer = "random_uniform",activation="relu"))
categorical.add(Dense(units = 7,kernel_initializer = "random_uniform",activation="softmax"))
categorical.compile(optimizer="rmsprop",loss="categorical_crossentropy",metrics=["accuracy"])
history = categorical.fit(x_train,y_train,epochs=500,batch_size=32,validation_data=(x_test,y_test))

Epoch 1/500
4/4 [==============================] - 2s 111ms/step - loss: 1.9448 - accuracy: 0.2036 - val_loss: 1.9402 - val_accuracy: 0.4167
Epoch 2/500
4/4 [==============================] - 0s 22ms/step - loss: 1.9405 - accuracy: 0.3245 - val_loss: 1.9361 - val_accuracy: 0.4167
Epoch 3/500
4/4 [==============================] - 0s 21ms/step - loss: 1.9371 - accuracy: 0.3266 - val_loss: 1.9319 - val_accuracy: 0.4167
Epoch 4/500
4/4 [==============================] - 0s 20ms/step - loss: 1.9344 - accuracy: 0.3401 - val_loss: 1.9276 - val_accuracy: 0.4167
Epoch 5/500
4/4 [==============================] - 0s 21ms/step - loss: 1.9285 - accuracy: 0.3151 - val_loss: 1.9237 - val_accuracy: 0.4167
Epoch 6/500
4/4 [==============================] - 0s 19ms/step - loss: 1.9294 - accuracy: 0.2776 - val_loss: 1.9188 - val_accuracy: 0.4167
Epoch 7/500
4/4 [==============================] - 0s 22ms/step - loss: 1.9217 - accuracy: 0.3433 - val_loss: 1.9140 - val_accuracy: 0.4167
Epoch 8/500
4/4 [==

4/4 [==============================] - 0s 18ms/step - loss: 1.3657 - accuracy: 0.4021 - val_loss: 1.6085 - val_accuracy: 0.4375
Epoch 118/500
4/4 [==============================] - 0s 19ms/step - loss: 1.3770 - accuracy: 0.3856 - val_loss: 1.6128 - val_accuracy: 0.4375
Epoch 119/500
4/4 [==============================] - 0s 18ms/step - loss: 1.3403 - accuracy: 0.4319 - val_loss: 1.6135 - val_accuracy: 0.4375
Epoch 120/500
4/4 [==============================] - 0s 19ms/step - loss: 1.3542 - accuracy: 0.4407 - val_loss: 1.6180 - val_accuracy: 0.4375
Epoch 121/500
4/4 [==============================] - 0s 19ms/step - loss: 1.3947 - accuracy: 0.3995 - val_loss: 1.6234 - val_accuracy: 0.4375
Epoch 122/500
4/4 [==============================] - 0s 20ms/step - loss: 1.4715 - accuracy: 0.4089 - val_loss: 1.6114 - val_accuracy: 0.4375
Epoch 123/500
4/4 [==============================] - 0s 19ms/step - loss: 1.4181 - accuracy: 0.4173 - val_loss: 1.6132 - val_accuracy: 0.4375
Epoch 124/500
4/4 [=

Epoch 175/500
4/4 [==============================] - 0s 19ms/step - loss: 1.3478 - accuracy: 0.4323 - val_loss: 1.6694 - val_accuracy: 0.4375
Epoch 176/500
4/4 [==============================] - 0s 19ms/step - loss: 1.3250 - accuracy: 0.4146 - val_loss: 1.6817 - val_accuracy: 0.4375
Epoch 177/500
4/4 [==============================] - 0s 19ms/step - loss: 1.3023 - accuracy: 0.3996 - val_loss: 1.6728 - val_accuracy: 0.4375
Epoch 178/500
4/4 [==============================] - 0s 20ms/step - loss: 1.3739 - accuracy: 0.4501 - val_loss: 1.6681 - val_accuracy: 0.4375
Epoch 179/500
4/4 [==============================] - 0s 20ms/step - loss: 1.3317 - accuracy: 0.4094 - val_loss: 1.6617 - val_accuracy: 0.4375
Epoch 180/500
4/4 [==============================] - 0s 20ms/step - loss: 1.2935 - accuracy: 0.4308 - val_loss: 1.6723 - val_accuracy: 0.4375
Epoch 181/500
4/4 [==============================] - 0s 20ms/step - loss: 1.2964 - accuracy: 0.4318 - val_loss: 1.6686 - val_accuracy: 0.4375
Epoch 

Epoch 233/500
4/4 [==============================] - 0s 19ms/step - loss: 1.3604 - accuracy: 0.3834 - val_loss: 1.7103 - val_accuracy: 0.4583
Epoch 234/500
4/4 [==============================] - 0s 18ms/step - loss: 1.3016 - accuracy: 0.4251 - val_loss: 1.7094 - val_accuracy: 0.4583
Epoch 235/500
4/4 [==============================] - 0s 19ms/step - loss: 1.2982 - accuracy: 0.4412 - val_loss: 1.7021 - val_accuracy: 0.4583
Epoch 236/500
4/4 [==============================] - 0s 19ms/step - loss: 1.2549 - accuracy: 0.4157 - val_loss: 1.7040 - val_accuracy: 0.4583
Epoch 237/500
4/4 [==============================] - 0s 20ms/step - loss: 1.3294 - accuracy: 0.4412 - val_loss: 1.6898 - val_accuracy: 0.4583
Epoch 238/500
4/4 [==============================] - 0s 18ms/step - loss: 1.2775 - accuracy: 0.4501 - val_loss: 1.6971 - val_accuracy: 0.4583
Epoch 239/500
4/4 [==============================] - 0s 20ms/step - loss: 1.2787 - accuracy: 0.4459 - val_loss: 1.6989 - val_accuracy: 0.4583
Epoch 

Epoch 291/500
4/4 [==============================] - 0s 21ms/step - loss: 1.2351 - accuracy: 0.4724 - val_loss: 1.7730 - val_accuracy: 0.4583
Epoch 292/500
4/4 [==============================] - 0s 18ms/step - loss: 1.2553 - accuracy: 0.4334 - val_loss: 1.7835 - val_accuracy: 0.4583
Epoch 293/500
4/4 [==============================] - 0s 19ms/step - loss: 1.2540 - accuracy: 0.4094 - val_loss: 1.7933 - val_accuracy: 0.4583
Epoch 294/500
4/4 [==============================] - 0s 18ms/step - loss: 1.2648 - accuracy: 0.4240 - val_loss: 1.7862 - val_accuracy: 0.4583
Epoch 295/500
4/4 [==============================] - 0s 19ms/step - loss: 1.2789 - accuracy: 0.4319 - val_loss: 1.7945 - val_accuracy: 0.4583
Epoch 296/500
4/4 [==============================] - 0s 20ms/step - loss: 1.2550 - accuracy: 0.4053 - val_loss: 1.8155 - val_accuracy: 0.4583
Epoch 297/500
4/4 [==============================] - 0s 19ms/step - loss: 1.2641 - accuracy: 0.4027 - val_loss: 1.8158 - val_accuracy: 0.4583
Epoch 

Epoch 349/500
4/4 [==============================] - 0s 20ms/step - loss: 1.2086 - accuracy: 0.4469 - val_loss: 1.9945 - val_accuracy: 0.4583
Epoch 350/500
4/4 [==============================] - 0s 19ms/step - loss: 1.1880 - accuracy: 0.4230 - val_loss: 1.9932 - val_accuracy: 0.4583
Epoch 351/500
4/4 [==============================] - 0s 18ms/step - loss: 1.2046 - accuracy: 0.3902 - val_loss: 2.0078 - val_accuracy: 0.4583
Epoch 352/500
4/4 [==============================] - 0s 19ms/step - loss: 1.1516 - accuracy: 0.4646 - val_loss: 1.9959 - val_accuracy: 0.4583
Epoch 353/500
4/4 [==============================] - 0s 19ms/step - loss: 1.1744 - accuracy: 0.4427 - val_loss: 2.0298 - val_accuracy: 0.4583
Epoch 354/500
4/4 [==============================] - 0s 19ms/step - loss: 1.2098 - accuracy: 0.4084 - val_loss: 1.9971 - val_accuracy: 0.4583
Epoch 355/500
4/4 [==============================] - 0s 18ms/step - loss: 1.3293 - accuracy: 0.4277 - val_loss: 2.0261 - val_accuracy: 0.4583
Epoch 

Epoch 407/500
4/4 [==============================] - 0s 20ms/step - loss: 1.2131 - accuracy: 0.4681 - val_loss: 2.1857 - val_accuracy: 0.4792
Epoch 408/500
4/4 [==============================] - 0s 19ms/step - loss: 1.1612 - accuracy: 0.4999 - val_loss: 2.2105 - val_accuracy: 0.4792
Epoch 409/500
4/4 [==============================] - 0s 21ms/step - loss: 1.1836 - accuracy: 0.4453 - val_loss: 2.2336 - val_accuracy: 0.5000
Epoch 410/500
4/4 [==============================] - 0s 18ms/step - loss: 1.1674 - accuracy: 0.4311 - val_loss: 2.2238 - val_accuracy: 0.4583
Epoch 411/500
4/4 [==============================] - 0s 19ms/step - loss: 1.1618 - accuracy: 0.4702 - val_loss: 2.2279 - val_accuracy: 0.5000
Epoch 412/500
4/4 [==============================] - 0s 19ms/step - loss: 1.1328 - accuracy: 0.5122 - val_loss: 2.2515 - val_accuracy: 0.5417
Epoch 413/500
4/4 [==============================] - 0s 20ms/step - loss: 1.1484 - accuracy: 0.4750 - val_loss: 2.2383 - val_accuracy: 0.5000
Epoch 

Epoch 465/500
4/4 [==============================] - 0s 19ms/step - loss: 1.1538 - accuracy: 0.4565 - val_loss: 2.3899 - val_accuracy: 0.4792
Epoch 466/500
4/4 [==============================] - 0s 20ms/step - loss: 1.1698 - accuracy: 0.4841 - val_loss: 2.3892 - val_accuracy: 0.4792
Epoch 467/500
4/4 [==============================] - 0s 19ms/step - loss: 1.1616 - accuracy: 0.4972 - val_loss: 2.4096 - val_accuracy: 0.4792
Epoch 468/500
4/4 [==============================] - 0s 20ms/step - loss: 1.1550 - accuracy: 0.4987 - val_loss: 2.4280 - val_accuracy: 0.5000
Epoch 469/500
4/4 [==============================] - 0s 19ms/step - loss: 1.1833 - accuracy: 0.4722 - val_loss: 2.4152 - val_accuracy: 0.4792
Epoch 470/500
4/4 [==============================] - 0s 19ms/step - loss: 1.0623 - accuracy: 0.5123 - val_loss: 2.4256 - val_accuracy: 0.5208
Epoch 471/500
4/4 [==============================] - 0s 19ms/step - loss: 1.0877 - accuracy: 0.5044 - val_loss: 2.4344 - val_accuracy: 0.5000
Epoch 

In [30]:
yp = categorical.predict(sc.transform([[540,28.5,31,34,10.744,6.562]]))

In [31]:
yp

array([[4.2440724e-01, 2.0323993e-13, 5.2609771e-01, 3.2396785e-13,
        3.3716876e-02, 8.0919743e-11, 1.5778137e-02]], dtype=float32)

In [32]:
yp>0.5 # These are classes, whichever highest prob that is predicted

array([[False, False,  True, False, False, False, False]])

In [33]:
yp = categorical.predict_classes(sc.transform([[540,28.5,31,34,10.744,6.562]]))

/home/riddhirup/anaconda3/envs/tf-gpu/lib/python3.9/site-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [34]:
yp

array([2])

In [35]:
yp = np.argmax(categorical.predict_classes(sc.transform([[540,28.5,31,34,10.744,6.562]])))

/home/riddhirup/anaconda3/envs/tf-gpu/lib/python3.9/site-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [36]:
yp

0

In [37]:
index = ["bearm","parrki","pearch","pike","roach","whitefish","smelt"]

In [38]:
pred=index[yp]

In [39]:
pred

'bearm'