1. import dataset
2. read dataset
3. Handle missing values
4. split data in x and y
5. handle categorical data
6. split data to train and test
7. applying feature scaling
8. Integer,String -> String/Integer

In [4]:
import numpy as np
import pandas as pd

In [5]:
dataset = pd.read_csv('/home/riddhirup/Downloads/Churn_Modelling.csv')

In [6]:
dataset


RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
0             1    15634602   Hargrave          619    France  Female  42.0   
1             2    15647311       Hill          225       NaN  Female  41.0   
2             3    15619304       Onio          629    France  Female  42.0   
3             4    15701354       Boni          699    France  Female  39.0   
4             5    15737888   Mitchell          850     Spain  Female  43.0   
...         ...         ...        ...          ...       ...     ...   ...   
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [7]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          225       NaN  Female  41.0   
2          3    15619304      Onio          629    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850     Spain  Female  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [8]:
dataset.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

In [9]:
dataset.head(1)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [10]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender              True
Age                 True
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [11]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          1
Gender             1
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

1. drop column - null values more than 50%
2. fill with own value
3. fill with mean.median,mode

In [12]:
dataset.drop(["Geography"],axis=1) # axis = 1 deleting column, axis=0 deleting row

RowNumber  CustomerId    Surname  CreditScore  Gender   Age  Tenure  \
0             1    15634602   Hargrave          619  Female  42.0       2   
1             2    15647311       Hill          225  Female  41.0       1   
2             3    15619304       Onio          629  Female  42.0       8   
3             4    15701354       Boni          699  Female  39.0       1   
4             5    15737888   Mitchell          850  Female  43.0       2   
...         ...         ...        ...          ...     ...   ...     ...   
9995       9996    15606229   Obijiaku          771    Male  39.0       5   
9996       9997    15569892  Johnstone          516    Male  35.0      10   
9997       9998    15584532        Liu          709  Female  36.0       7   
9998       9999    15682355  Sabbatini          772    Male  42.0       3   
9999      10000    15628319     Walker          792  Female  28.0       4   

        Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0          0.00              1          1               1        101348.88   
1      83807.86              1          0               1        112542.58   
2     159660.80              3          1               0        113931.57   
3          0.00              2          0               0         93826.63   
4     125510.82              1          1               1         79084.10   
...         ...            ...        ...             ...              ...   
9995       0.00              2          1               0         96270.64   
9996   57369.61              1          1               1        101699.77   
9997       0.00              1          0               1         42085.58   
9998   75075.31              2          1               0         92888.52   
9999  130142.79              1          1               0         38190.78   

      Exited  
0          1  
1          0  
2          1  
3          0  
4          0  
...      ...  
9995       0  
9996       0  
9997       1  
9998       1  
9999       0  

[10000 rows x 13 columns]

In [13]:
dataset[dataset["Geography"].isnull()].index.tolist()

[1]

In [14]:
dataset.drop([1],axis=0) # inplace = true for permanent deletion

RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
0             1    15634602   Hargrave          619    France  Female  42.0   
2             3    15619304       Onio          629    France  Female  42.0   
3             4    15701354       Boni          699    France  Female  39.0   
4             5    15737888   Mitchell          850     Spain  Female  43.0   
5             6    15574012        Chu          645     Spain    Male  44.0   
...         ...         ...        ...          ...       ...     ...   ...   
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
5          8  113755.78              2          1               0   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
5           149756.71       1  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[9999 rows x 14 columns]

In [15]:
dataset.fillna(value="abc")

RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
0             1    15634602   Hargrave          619    France  Female  42.0   
1             2    15647311       Hill          225       abc  Female  41.0   
2             3    15619304       Onio          629    France  Female  42.0   
3             4    15701354       Boni          699    France  Female  39.0   
4             5    15737888   Mitchell          850     Spain  Female  43.0   
...         ...         ...        ...          ...       ...     ...   ...   
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [16]:
dataset["Geography"].fillna(value="abc")

0        France
1           abc
2        France
3        France
4         Spain
         ...   
9995     France
9996     France
9997     France
9998    Germany
9999     France
Name: Geography, Length: 10000, dtype: object

In [17]:
dataset["Geography"].fillna(dataset["Geography"].mode()[0],inplace=True)
dataset["Gender"].fillna(dataset["Geography"].mode()[0],inplace=True)
dataset["Age"].fillna(dataset["Age"].mean(),inplace=True)

In [18]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
0             1    15634602   Hargrave          619    France  Female  42.0   
1             2    15647311       Hill          225    France  Female  41.0   
2             3    15619304       Onio          629    France  Female  42.0   
3             4    15701354       Boni          699    France  Female  39.0   
4             5    15737888   Mitchell          850     Spain  Female  43.0   
...         ...         ...        ...          ...       ...     ...   ...   
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [19]:
df = pd.DataFrame([["a",56],["a",12],["d",67],["c",25],["a",89],["b",15],["b",15],["b",15]],columns = ["Alphabets","Dean"])

In [20]:
df

Alphabets  Dean
0         a    56
1         a    12
2         d    67
3         c    25
4         a    89
5         b    15
6         b    15
7         b    15

In [21]:
df["Dean"].mean()

36.75

In [22]:
df["Alphabets"].mode()

0    a
1    b
dtype: object

In [23]:
df["Alphabets"].mode()[0]

'a'

In [24]:
dataset["Geography"].mode()[0]

'France'

# Split the dataset

In [25]:
x = dataset.iloc[:,[4,7,6,5]] # if columns has to be skipped
x = dataset.iloc[:,3:13]
y = dataset.iloc[:,13]

In [26]:
x

CreditScore Geography  Gender   Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female  42.0       2       0.00              1   
1             225    France  Female  41.0       1   83807.86              1   
2             629    France  Female  42.0       8  159660.80              3   
3             699    France  Female  39.0       1       0.00              2   
4             850     Spain  Female  43.0       2  125510.82              1   
...           ...       ...     ...   ...     ...        ...            ...   
9995          771    France    Male  39.0       5       0.00              2   
9996          516    France    Male  35.0      10   57369.61              1   
9997          709    France  Female  36.0       7       0.00              1   
9998          772   Germany    Male  42.0       3   75075.31              2   
9999          792    France  Female  28.0       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [27]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [28]:
print(type(x),type(y))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>


In [29]:
x = dataset.iloc[:,3:13].values # convert to arrays
y = dataset.iloc[:,13].values

In [30]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [225, 'France', 'Female', ..., 0, 1, 112542.58],
       [629, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [31]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [32]:
print(type(x),type(y))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [33]:
# handling categorical data - converts data to binary format
# based on unique values in datasets, those number of binary values will be created

In [34]:
dataset["Geography"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [35]:
dataset["Gender"].unique()

array(['Female', 'Male', 'France'], dtype=object)

In [36]:
x.shape

(10000, 10)

In [37]:
from sklearn.preprocessing import OneHotEncoder

In [38]:
from sklearn.compose import ColumnTransformer


In [39]:
ct = ColumnTransformer([("oh",OneHotEncoder(),[1,2])],remainder="passthrough")

In [40]:
x = ct.fit_transform(x)

In [41]:
x[1]

array([1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 225, 41.0, 1, 83807.86, 1, 0, 1,
       112542.58], dtype=object)

In [42]:
x.shape

(10000, 14)

In [43]:
# age education occupation salary gender
# ct = ColumnTransformer([("oh",OneHotEncoder(),[1,2,4])],remainder="passthrough")


phd-10000 mtech-01000 btech-00100 none-00010 tenth-00001


female - 100
male - 010
gender - 001

In [44]:
x.shape

(10000, 14)

In [45]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 0.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [47]:
y.shape

(10000,)

In [48]:
from sklearn.model_selection import train_test_split

In [59]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [60]:
x_train.shape

(8000, 14)

In [61]:
x_test.shape

(2000, 14)

In [62]:
print(y_train.shape,y_test.shape)

(8000,) (2000,)


In [56]:
x1=[1,2,3,4,5,6,7,8,9,10]
y1=[11,12,13,14,15,16,17,18,19,20]

In [66]:
for i in range(5):
    x1_train,x1_test,y1_train,y1_test = train_test_split(x1,y1,test_size=0.2,random_state=0)
    print(x1_train)
    print(x1_test)
    print(y1_train)
    print(y1_test)
    print("**********")

[5, 10, 2, 7, 8, 4, 1, 6]
[3, 9]
[15, 20, 12, 17, 18, 14, 11, 16]
[13, 19]
**********
[5, 10, 2, 7, 8, 4, 1, 6]
[3, 9]
[15, 20, 12, 17, 18, 14, 11, 16]
[13, 19]
**********
[5, 10, 2, 7, 8, 4, 1, 6]
[3, 9]
[15, 20, 12, 17, 18, 14, 11, 16]
[13, 19]
**********
[5, 10, 2, 7, 8, 4, 1, 6]
[3, 9]
[15, 20, 12, 17, 18, 14, 11, 16]
[13, 19]
**********
[5, 10, 2, 7, 8, 4, 1, 6]
[3, 9]
[15, 20, 12, 17, 18, 14, 11, 16]
[13, 19]
**********


In [67]:
for i in range(5):
    x1_train,x1_test,y1_train,y1_test = train_test_split(x1,y1,test_size=0.2,)
    print(x1_train)
    print(x1_test)
    print(y1_train)
    print(y1_test)
    print("**********")

[1, 5, 4, 7, 3, 10, 2, 8]
[9, 6]
[11, 15, 14, 17, 13, 20, 12, 18]
[19, 16]
**********
[5, 4, 6, 7, 10, 3, 9, 2]
[1, 8]
[15, 14, 16, 17, 20, 13, 19, 12]
[11, 18]
**********
[7, 3, 1, 10, 2, 8, 5, 6]
[9, 4]
[17, 13, 11, 20, 12, 18, 15, 16]
[19, 14]
**********
[8, 2, 9, 4, 1, 7, 3, 10]
[6, 5]
[18, 12, 19, 14, 11, 17, 13, 20]
[16, 15]
**********
[7, 1, 10, 9, 2, 6, 3, 5]
[8, 4]
[17, 11, 20, 19, 12, 16, 13, 15]
[18, 14]
**********


In [68]:
# ideal to use same rows,values || random_state=0

In [70]:
from sklearn.preprocessing import StandardScaler

In [71]:
p=StandardScaler()

In [72]:
a = np.array([[1,2,3],[4,5,6],[45,67,43],[34,34,23]])

In [73]:
a = p.fit_transform(a)

In [74]:
a

array([[-1.05629547, -0.95207875, -0.98787834],
       [-0.89785115, -0.8378293 , -0.79971104],
       [ 1.26755456,  1.523326  ,  1.52101903],
       [ 0.68659205,  0.26658205,  0.26657035]])

In [75]:
sc=StandardScaler()

In [76]:
x_train = sc.fit_transform(x_train) # permanent transformation
x_test = sc.transform(x_test) # temporary

In [77]:
x_train

array([[-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [78]:
x_test

array([[-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
        -1.03227043,  1.61255917]])